name: Flask Cloudflared Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Update & Upgrade System
        run: |
          sudo apt update
          sudo apt -y upgrade

      - name: Install Python3 & Pip
        run: |
          sudo apt install -y python3 python3-pip

      - name: Install Requirements
        run: |
          pip3 install --upgrade pip
          pip3 install -r requirements.txt

      - name: Start Flask App in Background
        run: |
          nohup python3 app.py &

      - name: Download & Install Cloudflared
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      - name: Start Cloudflared Tunnel
        run: |
          cloudflared tunnel --url http://localhost:5005
